volumes:
  chrome-data:

services:
  browser:
    image: selenium/standalone-chrome:125.0
    shm_size: 2gb
    environment:
      - EXTRA_CHROME_ARGS=--password-store=basic
    volumes:
      - chrome-data:/home/seluser
    ports:
      - 127.0.0.1:7900:7900
      - 127.0.0.1:4444:4444
    restart: unless-stopped
  yt-dlp-host:
    build: ./yt-dlp
    ports:
      - 127.0.0.1:5001:5001
    volumes:
      - ./downloads:/app/downloads
      - ./jsons:/app/jsons
      - ./config.py:/app/config.py
      - ./youtube_cookies.txt:/app/youtube_cookies.txt
    environment:
      - FLASK_APP=src.server:app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    restart: unless-stopped